### ISSUE TITLE
ERROR [Error: Request aborted]

### ISSUE THREAD

**Issue by jsam** [tomitrescak/meteor-uploads#116] opened 2015-07-14 21:01 UTC
Hello,

I'm trying to setup meteor-uploads for some time now. I'm running Ubuntu 14.04 on DO deployed through meteor-up. When I deployed it my app is in /opt/<appname>/* as a "meteoruser".  The permissions of the folder .uploads are the same as the user running the process.

The problem is when I try to upload, in logs I get

`ERROR
[Error: Request aborted]`

My UploadServer is configured as such:

  `Meteor.startup ->
    UploadServer.init({
      tmpDir: process.env.PWD + '/.uploads/tmp',
      uploadDir: process.env.PWD + '/.uploads',
      checkCreateDirectories: true
    })`

And in mup the process get stepdowned to meteoruser. Where is the catch? Why my uploads are not getting uploaded to the server?

**Comment by tomitrescak** [comment] 2015-07-28 07:23
Possible duplicate of #114 
Create directories yourself and set permissions.

**Comment by tomitrescak** [comment] 2015-07-28 07:23
I'll close this for now, please reopen if need be.

**Closed by tomitrescak** 2015-07-28 07:23 UTC
