### ISSUE TITLE
Limiting uploads to specific filetypes

### ISSUE THREAD

**Issue by Dids** [tomitrescak/meteor-uploads#109] opened 2015-06-29 20:19 UTC
I'm using regex on the server to only allow specific files to be uploaded. This works, and results in an error when the client tries to upload.

If I try to use the "fileTypes" option for the uploader (client-side), I don't see it behaving any differently?

What would be the best way to trigger an error to the user before they even get a chance to press the upload button?

**Comment by nonissue** [comment] 2015-07-16 03:09
It works for me with the semantic-ui form implementation — in the file picker on OSX, I can only choose image files, everything else is greyed out, which I assume is the intended behaviour. However, the current drop zone implementation doesn't appear to validate filetypes, and instead anything dragged&dropped is uploaded. Which version are you using?

**Comment by Dids** [comment] 2015-07-16 10:28
I'm using Bootstrap + both types of uploaders. I did actually get the non-dropzone version to validate client-side (it was a regex error on my part), but not the Dropzone, so I guess we're on the same boat there.

**Comment by tomitrescak** [comment] 2015-07-20 06:22
There is a `validate` event, in which you get File object that you can work on with javascript. Look at the **validation** section of the documentation in [here](https://github.com/tomitrescak/meteor-uploads).

**Comment by tomitrescak** [comment] 2015-07-20 06:24
This is how validate method is used in the uploader on client:
https://github.com/tomitrescak/meteor-tomi-upload-jquery/blob/master/uploader.js#L201-L206

**Comment by tomitrescak** [comment] 2015-07-28 07:15
Closing for now .. if need be reopen please.

**Closed by tomitrescak** 2015-07-28 07:15 UTC
Labels: question
