### ISSUE TITLE
After update to Meteor 1.3, upload-jquery crashes on undefined 'window'

### ISSUE THREAD

**Issue by mnfilius** [tomitrescak/meteor-uploads#224] opened 2016-03-29 13:07 UTC
Please see the screenshot.

After a update to Meteor 1.3, the code crashes as shown on line 622 because 'window' is undefined.
Meteor 1.2 worked like a charm.

Any suggestions on how to procede?

Thanks
Mark

![screen shot 2016-03-29 at 23 01 13](https://cloud.githubusercontent.com/assets/3906493/14108818/493ee59e-f602-11e5-9943-9b1f0ef5d06d.png)

**Comment by ChrisJGayle** [comment] 2016-03-29 17:12
I am experiencing the same problem.

**Comment by trayhem** [comment] 2016-03-30 11:30
I may have a solution. 
Download the git master repo to your project_dir/packages directory.
Now add:
```
} else if (typeof exports === 'object') {
        // Node/CommonJS:
        factory(require('jquery'));
```
to the lib/jquery.fileupload.js:23 file. 

I've checked the original ([jquery-file-upload repository file](https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload.js)) and it works for my setup.

The problem is that the complete global window object seems not available to the package at runtime. As of 1.3 meteor has now complete nodejs support so the require function works.

The lib/jquery.iframe-transport.js file also contains now this else if condition but it seems not required for my setup.

**Comment by mnfilius** [comment] 2016-03-30 12:26
Hi Trayhem

Thanks! But unfortunately that's not working for my setup. After adding the extra lines (at line 27, not 23) to that file, the meteor startup fails with "While computing assigned variables" at the very end of that file.
What ever I do, the same result, even a very simple change (so no syntax errors etc).

Thanks again though!

**Comment by trayhem** [comment] 2016-03-30 12:33
Hi @mnfilius 
Sorry, my bad. Somehow I deleted parts of the source code. The original file says:
```
} else if (typeof exports === 'object') {
        // Node/CommonJS:
        factory(
            require('jquery'),
            require('./vendor/jquery.ui.widget')
        );
```

Perhaps you can simply replace the lib/jquery.fileupload.js file with [this one](https://raw.githubusercontent.com/blueimp/jQuery-File-Upload/master/js/jquery.fileupload.js)

**Comment by mnfilius** [comment] 2016-03-30 12:57
HI @trayhem 

Thanks for the quick reply :-)
I started again:
* meteor remove tomi:upload-jquery
* downloaded the repo to packages/<etc>
* replaced that file with yours
Meteor starts again, but the original problem is still there. Looking at the js, your code changes aren't there. Somehow Meteor seems to use the original code. Maybe cached?? Any ideas??


Thx
Mark

**Comment by trayhem** [comment] 2016-03-30 13:12
Hi @mnfilius 

You still need to add the package to the .meteor/packages file (just add "tomi:upload-jquery" to the bottom). Meteor will recognize your custom package and will not attempt to download the online version.

**Comment by mnfilius** [comment] 2016-03-31 12:25
HI @trayhem 

You're clever! But I'm not clever enough :-( 

Good tips: the line in the .meteor/packages file was ok, but the jquery.iframe-transport.js file causes an issue (I could see that in the header comments).
However after redoing the steps en editing both jquery.*.js files, still the same issue: the edited files don't appear in the debug screen in Chrome (tab Sources). Next step is make a new app to test the caching, but I'm not hopeful.

Another thought is to get the (almost the) same package through npm, now that Meteor1.3 supports that. Do you have any idea if that would make a difference?

Cheers
Mark

**Comment by trayhem** [comment] 2016-03-31 13:51
Hi @mnfilius 

My init setup looks as following
On the server side:
```
Meteor.isServer(){
    Meteor.startup(function () {
        UploadServer.init(initObject);
    }
}
```
And on the client side:
```
Template.myTemplate.onCreated(function(){
    Uploader.init(this);
}
```
This works fine for me. The Uploader function is defined in the tomi-upload-jquery/uploader.js file.
Did you replace the complete files with the original ones or only the few code sequences containing the else if statement?
If you replaced the complete files, perhaps something else has changed in those files and the Uploader function is not called properly.

Unfortunately I'm not very familiar with installing npm packages to meteor. Sorry I can't help you with this.

**Comment by misteio** [comment] 2016-04-02 09:43
Thank you @trayhem , it works :)

**Comment by trayhem** [comment] 2016-04-03 09:45
Glad I could help @misteio :)

**Comment by tomitrescak** [comment] 2016-04-03 21:47
Sorry about delayed response as I did not have resources to work on this till now. Please update your project to latest version and all should be fixed. I am using now the latest version of Blueimps plugin. Unfortunately I cannot use the NPM dependency directly as Meteor does not yet support asset imports. I am also working on a NPM version that will be focused on React users not wanting to use Blaze templates.

**Closed by tomitrescak** 2016-04-03 21:47 UTC

**Comment by mnfilius** [comment] 2016-04-04 12:42
works again thanks!


Tomas Trescak wrote:

Sorry about delayed response as I did not have resources to work on this till now. Please update your project to latest version and all should be fixed. I am using now the latest version of Blueimps plugin. Unfortunately I cannot use the NPM dependency directly as Meteor does not yet support asset imports. I am also working on a NPM version that will be focused on React users not wanting to use Blaze templates.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/tomitrescak/meteor-uploads/issues/224#issuecomment-205061061>


Kind regards
Mark Filius
E: mark@filius.cc<mailto:mark@filius.cc>
P: +61 (0)7 3901 8014
M: +61 (0)4 1 3456 832
S: markfilius

**Comment by mnfilius** [comment] 2016-04-04 12:43
the new version works again, thanks to all (@trayhem) for all the help

**Comment by jykae** [comment] 2016-05-23 12:38
@mnfilius What was the solution for this issue? I am getting this same error.

**Comment by jykae** [comment] 2016-05-23 13:11
Is the fix provided here, https://github.com/tomitrescak/meteor-tomi-upload-jquery I can't see that the release for upload jquery matches with Atmosphere.

Versions I am using are:
tomi:upload-jquery@2.4.0
tomi:upload-server@1.3.4

**Comment by jykae** [comment] 2016-05-23 13:36
Would it work to use https://www.npmjs.com/package/blueimp-file-upload with upload-server package?

**Comment by jykae** [comment] 2016-05-23 14:19
We updated our project to Meteor 1.3.2.4 and error disappeared.
