### ISSUE TITLE
Upload file with cURL

### ISSUE THREAD

**Issue by samu79** [tomitrescak/meteor-uploads#61] opened 2015-03-13 16:14 UTC
Good morning,

when I try to use this command:

**curl -v -X POST 'http://127.0.0.1:3000/upload/' -H 'Content-Type: text/plain' -T "file.txt"**

I get the following answer:

* * Hostname was NOT found in DNS cache
* *   Trying 127.0.0.1...
* * Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
* > POST /upload/file.txt HTTP/1.1
* > User-Agent: curl/7.37.1
* > Host: 127.0.0.1:3000
* > Accept: */*
* > Content-Type: text/plain; charset=UTF-8
* > Content-Length: 1212
* > Expect: 100-continue
* > 
* < HTTP/1.1 100 Continue
* * We are completely uploaded and fine

but the output of the server says:

**[Error: bad content-type header, unknown content-type: text/plain]**

This is my javascript code:
```javascript
Meteor.startup(function () {
	UploadServer.init({
    tmpDir: '/Users/user/Documents/Uploads/tmp',
    uploadDir: '/Users/user/Documents/Uploads/',
    uploadUrl: '/upload/',
    checkCreateDirectories: true,
    acceptFileTypes: '.(txt|xml)',
    getDirectory: function(fileInfo, formData) {
      // create a sub-directory in the uploadDir based on the content type (e.g. 'images')
      console.log(fileInfo);
      console.log(fileInfo.type);
      return fileInfo.type;
    },
    finished: function(fileInfo, formFields) {
      // perform a disk operation
    },
    cacheTime: 100,
    mimeTypes: {
        "xml": "application/xml",
        "vcf": "text/x-vcard",
        "txt": "text/plain"
    }
  })
});
```

Could you please tell me where is the mistake?

Thank you

Regards.

**Comment by tomitrescak** [comment] 2015-03-13 21:40
Can you submit minimally reproducible application? Was not able to reproduce this behaviour on my configuration.

**Comment by samu79** [comment] 2015-03-13 22:26
Ok, 

The project tree is:

UFDemo folder
---- client folder
-------- init.js
---- server folder
-------- init.js
---- UFDemo.css (empty file)
---- UFDemo.html
---- UFDemo.js (empty file)

this is the *init.js* under *server* folder

```javascript
Meteor.startup(function () {
	UploadServer.init({
    tmpDir: '/Users/user/Documents/Uploads/tmp',
    uploadDir: '/Users/user/Documents/Uploads/',
    uploadUrl: '/upload/',
    checkCreateDirectories: true,
    getDirectory: function(fileInfo, formData) {
      // create a sub-directory in the uploadDir based on the content type (e.g. 'images')
      console.log(fileInfo);
      console.log(fileInfo.type);
      return fileInfo.type;
    },
    finished: function(fileInfo, formFields) {
      // perform a disk operation
      console.log("Upload finished");
    },
    cacheTime: 100
  })
});
```

and this is the *init.js* under *client* folder

```javascript
Meteor.startup(function() {
  Uploader.uploadUrl = Meteor.absoluteUrl("upload"); // Cordova needs absolute URL
});
```

This is the mail file *UFDemo.js* under *root project* folder

```javascript
<head>
  <title>UFDemo</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>
  {{> ufdemo}}
</body>

<template name="ufdemo">
	{{> upload_bootstrap }}
</template>
```

These are the packages installed:

* accounts-base       1.1.3  A user account system
* accounts-password   1.0.6  Password support for accounts
* accounts-ui         1.1.4  Simple templates to add login widgets to an app
* autopublish         1.0.2  Publish the entire database to all clients
* ian:bootstrap-3     3.3.1  HTML, CSS, and JS framework for developing responsive, mobile first projects on the web.
* insecure            1.0.2  Allow all database writes by default
* iron:router         1.0.7  Routing specifically designed for Meteor
* meteor-platform     1.2.1  Include a standard set of Meteor packages in your app
* nimble:restivus     0.6.2  Create authenticated REST APIs in Meteor 0.9.0+. Setup CRUD endpoints for Collections.
* tomi:upload-jquery  2.1.2* Client template for uploads using "jquery-file-upload" from blueimp
* tomi:upload-server  1.2.2  Upload server for Meteor. Allows to save and serve files (Breaking changes from 1.0.3)

In a terminal, I have run this command:

**curl -v -X POST "http://127.0.0.1:3000/upload" -H "Content-Type:text/plain" -T "file.txt"**

with the following answer:

* * Hostname was NOT found in DNS cache
* *   Trying 127.0.0.1...
* * Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
* > POST /upload/file.txt HTTP/1.1
* > User-Agent: curl/7.37.1
* > Host: 127.0.0.1:3000
* > Accept: */*
* > Content-Type:text/plain
* > Content-Length: 1212
* > Expect: 100-continue
* > 
* < HTTP/1.1 100 Continue
* * We are completely uploaded and fine

However, the console of meteor says:

**[Error: bad content-type header, unknown content-type: text/plain]**

Could you please help me?

Thank you

Regards

**Comment by tomitrescak** [comment] 2015-03-14 23:35
Hi, I gave it an hour and could not solve it. The problem is not on my side, it is in the way you are calling for upload from curl. I can report to you, that the error is raised by the "formidable" package, that cancels your download in the beginning when it is validating the POST request. Sorry I can't be of much more help but this is very specific for your case :/ Please report your findings if you manage to solve this.

**Comment by tomitrescak** [comment] 2015-03-18 02:48
Any success on the issue?

**Comment by samu79** [comment] 2015-03-18 08:10
Hi,
with the following command:
**curl -v -X POST "http://127.0.0.1:3000/upload" -H "Content-Type:application/json" -T "download.jpeg"**
I was able to upload a file.
I have changed the Content-Type to *application/json*, and it works.

**Comment by tomitrescak** [comment] 2015-03-18 10:50
Great! Thanks! There is another user that will benefit from your findings ;)

**Comment by tomitrescak** [comment] 2015-03-18 10:51
I will close this issue, you can reopen if necessary.

**Closed by tomitrescak** 2015-03-18 10:51 UTC
