### ISSUE TITLE
upload_semantic_ui does not call init() and other problems.

### ISSUE THREAD

**Issue by n17r4m** [tomitrescak/meteor-uploads#17] opened 2014-12-30 06:44 UTC
I'm trying out your controls and I gotta say, if I could iron out some the issues.. It would exactly what I am looking for in my app!

Looking at your projects history, I think that since upload_bootstrap has been revamped, semantic_ui has taken a few blows,

The first problem I've ran into is that the .created() is not being applied, so globalInfo is undefined, since init() isn't being called.

Suggestion: add --- 8< ---

Template['upload_semantic_ui'].created = function () {
	Uploader.init.call(this);
};

--- 8< --- to meteor-tomi-upload-jquery/upload_semantic_ui.js

And that seemed to fix the undeclared variables issue, however, even after that there are some troubles getting the upload to actually happen. I'm looking into it further, but I thought I would share what I got so far.

**Comment by tomitrescak** [comment] 2015-01-22 23:35
You probably got this sorted by now, but the new version 2.0.0 contains a full support for semantic UI. Closing issue.

**Closed by tomitrescak** 2015-01-22 23:35 UTC

**Comment by sunstorymvp** [comment] 2015-02-24 21:14
same problem with both templates, bootstrap and semantic.
versions:
tomi:upload-jquery@2.0.3
tomi:upload-server@1.2.1

**Comment by tomitrescak** [comment] 2015-02-24 21:16
Need more info. Init is called only internally to initialise the template and it is correctly called.

**Comment by sunstorymvp** [comment] 2015-02-24 21:19
the core problem is 

 Uncaught TypeError: Cannot read property 'set' of undefined

at

      change: function (e, data) { // called when input selection changes (file selected)
        // clear the queue, this is used to visualise all the data
        templateContext.queue = [];
        templateContext.queue.size = 0;
        templateContext.progressBar.css('width', '0%');
        templateContext.globalInfo.set({running: false, progress: 0});


while adding new file. globalInfo is undefined

**Comment by tomitrescak** [comment] 2015-02-24 21:21
Hmmm, I need minimally reproducible app for that :/ This problem should not happen since it was specifically targeted at 2.0.1.

**Comment by sunstorymvp** [comment] 2015-02-24 21:28
sure.
https://freevotal-sunstorymvp.c9.io/

login with admin@example.com / password 
open any project and try to upload file (find "Browse...")

source code is here https://ide.c9.io/sunstorymvp/freevotal

i'm learning meteor so all it is open for anyone

**Comment by sunstorymvp** [comment] 2015-02-24 21:52
is it too complicated project? if so, I can create a small project with only reproduce the problem.

**Comment by tomitrescak** [comment] 2015-02-24 21:57
Dmitri, smaller project would be nice, with these more complicated project your errors can kick in and then it's about debugging. I need to find package errors. Thanks!

**Comment by sunstorymvp** [comment] 2015-02-24 22:06
ok. this is it
https://file-upload-problem-sunstorymvp.c9.io/
https://ide.c9.io/sunstorymvp/file_upload_problem

**Comment by tomitrescak** [comment] 2015-02-25 02:24
Everything works fine for me if I remove following unnecessary call from the `upload.js` file

```javascript
if (Meteor.isClient) {
  Template.fileUpload.rendered = function(){
    Uploader.render.call(this);
  }
}
```

**Comment by tomitrescak** [comment] 2015-02-25 02:25
Where did you read that you need to call that?

**Comment by sunstorymvp** [comment] 2015-02-25 10:50
oh it's my fault! I forgot to remove this line of code after tried to create own template.
I followed this guide https://doctorllama.wordpress.com/2014/11/06/meteor-upload-package-with-jquery-file-upload/

thanks a lot!

**Comment by sunstorymvp** [comment] 2015-02-25 11:52
to make the conversation more useful to other people, please tell me what I am doing wrong in case of creating own template.

1. define template with form tag that includes:
 element with class .uploadFilePicker holding the file picker
 element with class .uploadProgressHolder holding the file picker
 element with class .uploadProgressBar showing the progress bar
 element with class .uploadProgressLabel showing the progress label
2. call
 Template['your_upload_template'].rendered = function () {
   Uploader.render.call(this);
 };

... and nothing happens when i'm choosing file.

I updated the project and git repository

**Comment by tomitrescak** [comment] 2015-02-26 12:28
Dmitri, here is an example of a custom template. I do not have time now, but soon I will update the documentation.

Tamplate:
```html
<template name="customUpload">
    <form method="POST" enctype="multipart/form-data">
        <input type="file" class="jqUploadclass" data-form-data='{{ submitData }}'>
        {{#with infoLabel}}
            {{ infoLabel}} <button class="start">StartUpload</button>
            <div style="width: 200px; height: 30px; border: 1px solid black">
                <div style="background: red; height: 30px; width: {{ progress }}">
                    {{ progress }}
                </div>
            </div>
        {{/with}}

    </form>
</template>
```

Javascript
```javascript
Template.customUpload.created = function() {
  Uploader.init(this);
}

Template.customUpload.rendered = function () {
  Uploader.render.call(this);
};

Template.customUpload.events({
  'click .start': function (e) {
    Uploader.startUpload.call(Template.instance(), e);
  }
});

Template.customUpload.helpers({
  'infoLabel': function() {
    var instance = Template.instance();

    // we may have not yet selected a file
    var info = instance.info.get()
    if (!info) {
      return;
    }

    var progress = instance.globalInfo.get();

    // we display different result when running or not
    return progress.running ?
      info.name + ' - ' + progress.progress + '% - [' + progress.bitrate + ']' :
      info.name + ' - ' + info.size + 'B';
  },
  'progress': function() {
    return Template.instance().globalInfo.get().progress + '%';
  }
})
```

**Comment by sunstorymvp** [comment] 2015-02-26 13:58
this is exactly what i need! thank for your help!

**Comment by mariyajames269** [comment] 2015-03-09 05:08
I followed instructions in the https://github.com/tomitrescak/meteor-uploads to upload an image. I was able to upload the image using the normal methods. but when i tried to use the custom template with the code above then  no files are  being selected. whether i have to make any other changes in the program
