### ISSUE TITLE
FileInfo on server vs client is missing the url field... ??

### ISSUE THREAD

**Issue by wesyah234** [tomitrescak/meteor-uploads#124] opened 2015-07-30 22:02 UTC
when I dump out the contents of the fileInfo object on the client during a file upload, I see: 
![screen shot 2015-07-30 at 5 00 34 pm](https://cloud.githubusercontent.com/assets/66566/8996298/8a3dda7c-36dc-11e5-9faf-aafd93cfb08c.jpg)
 
however, on the server, I don't see the url field when I dump the file object out:
![screen shot 2015-07-30 at 5 01 15 pm](https://cloud.githubusercontent.com/assets/66566/8996310/9d96cd68-36dc-11e5-8a6f-893d97c6772d.jpg)

just curious about that... Also, if I was going to build a URL myself, is it always http:// myserver/uploads/filename

ie, where does the /uploads part of the url come from .. is it hard coded in this package?

thanks!

**Comment by nonissue** [comment] 2015-08-04 02:46
Yah, I think I found this as well. I spent a few hours debugging (though this was a few weeks ago and my recollection is hazy) and I could not find a clear way to get the url field on the server. I figured out a work around, but I'm curious if this is intended behaviour or a bug.

**Comment by elfatherbrown** [comment] 2015-08-14 00:17
Same here. Very strange.

**Comment by tomitrescak** [comment] 2015-08-28 01:00
Agh, sorry for such a late response. You can set the upload url on server using `UploadServer.init({uploadUrl: 'YourCustomURL'}). The url is not generated on server callback, but if needed it can be added.

**Comment by tomitrescak** [comment] 2015-08-28 01:52
Ok, I have added this info in the new version `1.2.9.` Just update your project and FileInfo on server now contains following:

```json
{"name":"Test.gif",
"path":"Test.gif",
"size":862444,
"type":"image/gif",
"subDirectory":"",
"baseUrl":"http://localhost:3000/upload/",
"url":"http://localhost:3000/upload/Test.gif",
"error":null}
```

Hope it helps! I'll close this for now, please repoen if necessary.

**Closed by tomitrescak** 2015-08-28 01:52 UTC
