### ISSUE TITLE
503 Error

### ISSUE THREAD

**Issue by suhaboncukcu** [tomitrescak/meteor-uploads#30] opened 2015-02-02 17:11 UTC
I've decided to use your upload methods instead of collectionfs thingy however,

I am getting a 
    POST http://localhost:3000/upload 503 (Service Unavailable) 
error on upload. 

I followed the instructions as in readme. What could be the problem? 

Thanks for the work!

**Comment by conorstrejcek** [comment] 2015-02-02 19:05
I posted in #22 , but it might make sense to post this here as well. I'm having the same issue as well:

@tomitrescak I am having this issue as well, but it does not seem to be connected to Firebug or any other debug tool.

I get the same 503 error as @striletskyy , but on the server side I get: `TypeError: Converting circular structure to JSON`.

An object appears in the `.uploads/` folder, but it doesn't seem to be accessible.

The full trace for the `TypeError` looks like:

    /Users/<username>/dev/<appName>/.meteor/local/build/programs/server/packages/tomi_upload-server.js:146
    W20150202-08:15:48.459(-6)? (STDERR)           res.end(JSON.stringify(result));                                    
    W20150202-08:15:48.459(-6)? (STDERR)                        ^
    W20150202-08:15:48.459(-6)? (STDERR) TypeError: Converting circular structure to JSON
    W20150202-08:15:48.459(-6)? (STDERR)     at Object.stringify (native)
    W20150202-08:15:48.459(-6)? (STDERR)     at [object Object].handleResult [as callback] (packages/tomi:upload-server/upload_server.js:123:1)
    W20150202-08:15:48.460(-6)? (STDERR)     at IncomingForm.finish (packages/tomi:upload-server/upload_server.js:231:1)
    W20150202-08:15:48.461(-6)? (STDERR)     at IncomingForm.emit (events.js:92:17)
    W20150202-08:15:48.461(-6)? (STDERR)     at IncomingForm._maybeEnd (/Users/<username>/.meteor/packages/tomi_upload-server/.1.1.0.17cg4ze++os+web.browser+web.cordova/npm/node_modules/formidable/lib/incoming_form.js:551:8)
    W20150202-08:15:48.461(-6)? (STDERR)     at /Users/<username>/.meteor/packages/tomi_upload-server/.1.1.0.17cg4ze++os+web.browser+web.cordova/npm/node_modules/formidable/lib/incoming_form.js:229:12
    W20150202-08:15:48.461(-6)? (STDERR)     at WriteStream.<anonymous> (/Users/<username>/.meteor/packages/tomi_upload-server/.1.1.0.17cg4ze++os+web.browser+web.cordova/npm/node_modules/formidable/lib/file.js:70:5)
    W20150202-08:15:48.461(-6)? (STDERR)     at WriteStream.g (events.js:180:16)
    W20150202-08:15:48.462(-6)? (STDERR)     at WriteStream.emit (events.js:117:20)
    W20150202-08:15:48.462(-6)? (STDERR)     at finishMaybe (_stream_writable.js:359:12)
    W20150202-08:15:48.462(-6)? (STDERR)     at afterWrite (_stream_writable.js:279:5)

**Comment by suhaboncukcu** [comment] 2015-02-02 19:13
@conorstrejcek ; 

I have the exact trace with exact object thing. 

So I assume we have the same problem. Thanks for joining so I don't feel so lost now, at least I'm not the only one. :+1:

**Comment by tomitrescak** [comment] 2015-02-02 20:26
guys, thanks for reporting this, please, can you create a minimally reproducible application? Cannot seem to reproduce the error.

**Comment by conorstrejcek** [comment] 2015-02-02 20:47
@tomitrescak Where would be a good place to upload the application?

**Comment by tomitrescak** [comment] 2015-02-02 20:51
Conor, just reproduced it, will correct it in next 2 hours and upload a patch.

**Comment by conorstrejcek** [comment] 2015-02-02 20:56
@tomitrescak Thank you! You are doing some very helpful work.

**Comment by tomitrescak** [comment] 2015-02-02 21:37
Ok guys, get the latest version of server, should be 1.1.1. There was a bug
related to the breaking changes, when no callback on the file name was set,
the default one was producing circular nonsense. Please let me know if
everything is now in orders
.

**Comment by suhaboncukcu** [comment] 2015-02-02 21:48
Thanks a lot! 

It works perfectly now.

**Comment by tomitrescak** [comment] 2015-02-04 06:04
Great! I will close this issue now.

**Closed by tomitrescak** 2015-02-04 06:04 UTC
