### ISSUE TITLE
localisation 

### ISSUE THREAD

**Issue by tomvolek** [tomitrescak/meteor-uploads#168] opened 2015-10-15 08:10 UTC
How do I localise the text on the UI ?   I am doing  the following , but don't see any text getting translated. 

Uploader.localisation = {
            browse: "فهرست",
            cancelled: i18n("Cancelled"),
            remove: i18n("Remove"),
            upload: "Upload",
            done: i18n("Done"),
            cancel: i18n("Cancel")
        }

**Comment by tomitrescak** [comment] 2015-10-15 23:12
Duplicate of #167

**Closed by tomitrescak** 2015-10-15 23:12 UTC
